name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Build docker image
      uses:  appleboy/ssh-action@master
      with:
        host: 52.76.70.216
        username: ubuntu
        key: ${{ secrets.MYKEY }}
        port: 22
        script: |
          sh build-image.sh
